@startuml

start
:Declare two variables for input;
:Get two integer input from user and store them in those variables;
if(is number2 multiple of number1?) then (Yes)
: Display number2 is a multiple of number1;
else (No)
: Display number2 is not a multiple of number1;
endif
stop

@enduml